name: CI learn

on:
  # push:
  #   branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test > test_report.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: test_report
          path: test_report.txt



      