name: Manual Deployment

on:
    workflow_dispatch:
        inputs:
            target_env:
                description: 'Target environment for deployment'
                type: choice
                options:
                    - dev
                    - staging
                    - test
                    - prod

            target_env_github:
                description: 'Target environment from Github'
                type: environment
                required: true

            version:
                description: 'Deployment version'
                type: string
                required: false
                default: 'latest'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            target_env: ${{ github.event.inputs.target_env }}
        steps:
            - run: echo "Building application...in environment ${{ env.target_env }}"

    deploy:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Deploy
              run: |
                echo "Deploying the application's current build with version: ${{ github.event.inputs.version }}"
                # Deployment script goes here
