name: Professional CI

on:
    pull_request:
        branches: ["main"]
    push:
        branches: ["main"]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v4.0.3
              with:
                node-version: "24"
                cache: "npm"
            - run: npm ci
            - name: Run lint only on PR
              if: github.event_name == 'pull_request'
              run: npm run lint

    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ["20", "24"]
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v4.0.3
              with:
                node-version: ${{ matrix.node-version }}
                cache: "npm"
            - run: npm ci
            - run: npm test > report.txt
            - uses: actions/upload-artifact@v7.0.0
              with:
                name: test-report-${{ matrix.node-version }}
                path: report.txt

    build:
        needs: [lint, test]
        runs-on: ubuntu-latest
        steps:
            - run: echo "Building application..."

    build-image:
        needs: [lint, test]
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Check Docker Version
              run: docker --version

            - name: Inspect environment
              run: |
                uname -a
                node -v
                docker --version

            - name: Build docker image
              run: docker build -t sum-app .

            - name: Save docker image
              run: docker save sum-app > sum-image.tar

            - uses: actions/upload-artifact@v7.0.0
              with:
                name: docker_image
                path: sum_image.tar

